bampfaex/config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  resources :people
  resources :series
  resources :events
  resources :works
  get 'calendar' => "simple_calendar#index" 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bampfaex/app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: %i[ show edit update destroy ]

  # GET /series or /series.json
  def index
    @series = Series.all
  end

  # GET /series/1 or /series/1.json
  def show
  end

  # GET /series/new
  def new
    @series = Series.new
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series or /series.json
  def create
    @series = Series.new(series_params)

    respond_to do |format|
      if @series.save
        format.html { redirect_to series_url(@series), notice: "Series was successfully created." }
        format.json { render :show, status: :created, location: @series }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1 or /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to series_url(@series), notice: "Series was successfully updated." }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1 or /series/1.json
  def destroy
    @series.destroy

    respond_to do |format|
      format.html { redirect_to series_index_url, notice: "Series was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def series_params
      params.require(:series).permit(:series_start_date, :series_end_date, :series_type, :series_title, :series_description, :series_credits, :series_short_description)
    end
end

bampfaex/app/helpers/series_helper.rb
module SeriesHelper
  def list_series_people(series_id: @series_id,role: @role)
    # query for related people and return an array of hashes
    people_relations = Relation.select("person_id").where(series_id: series_id, relation_value: role).all
    people = []
    people_relations.each do |p|
      begin
        person = Person.find(p.person_id)
        people << person
      rescue ActiveRecord::RecordNotFound
        puts "#{people}not found"
      end
    end
    return people
  end

  def list_series_relations(series_id: nil, target_model: nil, role: nil)
    # query for related people and return an array of hashes
    _id = target_model.to_s+"_id"
    target_id_label = _id.downcase
    model_name = target_model.constantize
    _relations = Relation.select(target_id_label).where(series_id: series_id, relation_value: role).all
    unless _relations.to_a == []
      relateds = []
      _relations.each do |r|
        target_id = r.as_json[target_id_label]
        related = model_name.find(target_id)
        relateds << related
      end
      puts relateds
    end
    return relateds
  end

  def get_resourcespace_image_previews(series_id)
    _series = Series.find(series_id)
    series_title = _series.series_title
    unless series_title.nil?
      # extend ResourcespaceHelper
      request = ResourcespaceHelper::RSpaceRequest.new
      response = request.search_get_previews(search_string="#{series_title}",resource_type=2)
      # puts response

    end

  end
end

bampfaex/app/views/series/_form.html.erb
<%= form_with(model: series, local: true) do |form| %>
  <% if series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% series.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :series_start_date %>
    <%= form.datetime_select :series_start_date %>
  </div>

  <div class="field">
    <%= form.label :series_end_date %>
    <%= form.datetime_select :series_end_date %>
  </div>

  <div class="field">
    <%= form.label :series_type %>
    <%= form.text_field :series_type %>
  </div>

  <div class="field">
    <%= form.label :series_title %>
    <%= form.text_field :series_title %>
  </div>

  <div class="field">
    <%= form.label :series_description %>
    <%= form.text_area :series_description %>
  </div>

  <div class="field">
    <%= form.label :series_credits %>
    <%= form.text_area :series_credits %>
  </div>

  <div class="field">
    <%= form.label :series_short_description %>
    <%= form.text_area :series_short_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

bampfaex/app/views/series/edit.html.erb
<h1>Editing Series</h1>

<%= render 'form', series: @series %>

<%= link_to 'Show', @series %> |
<%= link_to 'Back', series_index_path %>

bampfaex/app/views/series/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Series</h1>

<table>
  <thead>
    <tr>
      <th>Series start date</th>
      <th>Series end date</th>
      <th>Series type</th>
      <th>Series title</th>
      <th>Series description</th>
      <th>Series credits</th>
      <th>Series short description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @series.each do |series| %>
      <tr>
        <td><%= series.start_date_display %></td>
        <td><%= series.end_date_display %></td>
        <td><%= series.series_type %></td>
        <td><%= series.series_title %></td>
        <td><%= link_to 'Show', series %></td>
        <td><%= link_to 'Edit', edit_series_path(series) %></td>
        <td><%= link_to 'Destroy', series, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Series', new_series_path %>

bampfaex/app/views/series/new.html.erb
<h1>New Series</h1>

<%= render 'form', series: @series %>

<%= link_to 'Back', series_index_path %>

bampfaex/app/views/series/show.html.erb
<div class="container-fluid">
  <div class="row mt-3 content-area">
    <div class="col-md-8">
      <!-- image and related events column -->
      <% @preview_tags = get_resourcespace_image_previews(@series.id) %>
      <% unless @preview_tags.nil? %>
        <div class="row">
          <div class="col-sm">
            <%= render partial: "/layouts/preview_carousel", locals: {preview_tags: @preview_tags} %>
          </div>
        </div>
      <% end %>
      <% exhibition_events = list_series_relations(series_id: @series.id, target_model: "Event", role: 'related exhibition') %>
      <% screenings = list_series_relations(series_id: @series.id, target_model: "Event", role: 'film series') %>
      <% unless exhibition_events.to_a.empty? %>
      <div class="row">
        <div class="col-sm">
          <div class="card event-info-box my-3">
            <div class="card-body rounded related-stuff-card">
              <h2>Related Events:</h2>
              <%= safe_join(exhibition_events.map { |p| link_to(p.display_date, "/events/#{p.id}") }, ", ".html_safe) %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
      <% unless screenings.to_a.empty? %>
      <div class="row">
        <div class="col-sm">
          <div class="card event-info-box my-3">
            <div class="card-body rounded related-stuff-card">
              <h2>Screenings in this series</h2>
              <%= safe_join(screenings.map { |p| link_to(p.display_date, "/events/#{p.id}") }, ", ".html_safe) %>
            </div>
          </div>
        </div>
      </div>
      <% end %>

    </div>
    <div class="col-md-4 related-stuff">
      <!-- title and description column -->
      <div class="row">
        <div class="col">
          <div class="card mt-3 rounded">
            <div class="card-body rounded related-stuff-card">
              <h2><%= @series.series_title %></h2>
              <h4><%= @series.start_date_display() %> — <%= @series.end_date_display() %></h4>
              <h5><%= @series.series_type %></h5>
              <% unless @series.location.nil? %>
                <h5><%= @series.location %></h5>
              <% end %>
              <% curators = list_series_people(series_id: @series.id, role: 'curator') %>
              <% unless curators.to_a.empty? %>
                <h4>Curated by <%= safe_join(curators.map { |p| link_to(p.display_name, "/people/#{p.id}") }, ", ".html_safe) %></h4>
              <% end %>
              <% artists = list_series_people(series_id: @series.id, role: 'artist') %>
              <% unless artists.to_a.empty? %>
                <h4>Artists: <%= safe_join(artists.map { |p| link_to(p.display_name, "/people/#{p.id}") }, ", ".html_safe) %></h4>
              <% end %>
              <% unless @series.outside_organizer.nil? %>
                <h5>Organized by <%= @series.outside_organizer %></h5>
              <% end %>
              <% unless @series.series_credits.nil? %>
                <h5>Credits: <%= @series.series_credits %></h5>
              <% end %>
            </div>
          </div>
          <% unless @series.series_description.nil? %>
          <div class="card my-3 rounded">
            <div class="card-body rounded related-stuff-card">
                <%= @series.series_description %>
            </div>
          </div>
          <% end %>
      </div>
  </div>
</div>

<!-- <p>
  <strong>Series short description:</strong>
  <%= @series.series_short_description %>
</p> -->
<div>
  <%= link_to 'Edit', edit_series_path(@series) %> |
  <%= link_to 'Back', series_index_path %>
</div>