bampfaex/config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  resources :people
  resources :series
  resources :events
  resources :works
  get 'calendar' => "simple_calendar#index" 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bampfaex/app/models/work.rb
class Work < ApplicationRecord

  has_many :relations

  has_many :people, :through => :relations

  belongs_to :series, optional: true
  belongs_to :event, optional: true

  validates_uniqueness_of :title, scope: [:wikidata_id]

  def make_unique_combo
    _title = (self.title || "")
    _year = (self.year || "")
    _wikidata_id = (self.wikidata_id||"")
    @unique_combo = "#{self.title}#{self.year}#{self.wikidata_id}"

    _title << _year << _wikidata_id
  end

end

bampfaex/app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: %i[ show edit update destroy ]

  # GET /works or /works.json
  def index
    @works = Work.all

  end

  # GET /works/1 or /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works or /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to work_url(@work), notice: "Work was successfully created." }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1 or /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to work_url(@work), notice: "Work was successfully updated." }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1 or /works/1.json
  def destroy
    @work.destroy

    respond_to do |format|
      format.html { redirect_to works_url, notice: "Work was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def work_params
      params.require(:work).permit(:year, :description, :title)
    end
end

bampfaex/app/helpers/works_helper.rb
module WorksHelper
  def list_work_people(work_id: @work_id,role: @role)
    # query for related people and return an array of hashes
    people_relations = Relation.select("person_id").where(work_id: work_id, relation_value: role).all
    people = []
    people_relations.each do |p|
      begin
        person = Person.find(p.person_id)
        people << person
      rescue ActiveRecord::RecordNotFound
        puts "#{people}not found"
      end
    end
    return people
  end
  def list_work_events(work_id: @work_id,role: @role)
    # query for related events and return an array of hashes
    events_relations = Relation.select("event_id").where(work_id: work_id, relation_value: role).all
    events = []
    events_relations.each do |p|
      begin
        event = Event.find(p.event_id)
        events << event
      rescue ActiveRecord::RecordNotFound
        puts "#{events}not found"
      end
    end
    return events
  end

  def render_thumb_link(blob_csid, doc_id)
    doc_url = "https://cinefiles.bampfa.berkeley.edu/catalog/#{doc_id}"
    thumb_url= "https://webapps.cspace.berkeley.edu/cinefiles/imageserver/blobs/#{blob_csid}/derivatives/Medium/content"
    tag = "<a href='#{doc_url}'><img class='' style='max-width: 200px' src='#{thumb_url}'></a>"
  end

  def list_cinefiles_thumbs(film_title: @film_title)
    film_title = CGI.escape film_title
    url = URI.parse("https://webapps.cspace.berkeley.edu/solr/cinefiles-public/select?q=title_ss:%22#{film_title}%22")
    puts url
    req = Net::HTTP::Get.new(url.to_s)
    res = Net::HTTP.start(url.host, url.port,use_ssl: true) {|http| http.request(req) }
    hash_response = JSON.parse(res.body)
    docs = hash_response['response']['docs']
    puts docs
    thumbs = []
    docs.each do |doc|
      doc_id = doc['id']
      blob_csid = doc['blob_ss'][0]
      thumb_link = render_thumb_link(blob_csid,doc_id)
      thumbs << thumb_link
    end
    return thumbs
  end
end

bampfaex/app/views/works/_form.html.erb
<%= form_with(model: work, local: true) do |form| %>
  <% if work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

bampfaex/app/views/works/edit.html.erb
<h1>Editing Work</h1>

<%= render 'form', work: @work %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

bampfaex/app/views/works/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Works</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @works.each do |work| %>
      <tr>
        <td><%= work.year %></td>
        <td><%= work.title %></td>
        <td><%= work.description %></td>
        <td><%= link_to 'Show', work %></td>
        <td><%= link_to 'Edit', edit_work_path(work) %></td>
        <td><%= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work', new_work_path %>

bampfaex/app/views/works/new.html.erb
<h1>New Work</h1>

<%= render 'form', work: @work %>

<%= link_to 'Back', works_path %>

bampfaex/app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @work.title %>
</p>

<p>
  <strong>Alternative Title:</strong>
  <%= @work.alt_title %>
</p>

<p>
  <strong>Director:</strong>
  <%= safe_join(list_work_people(work_id: @work.id, role: 'director').map { |p| link_to(p.display_name, "/people/#{p.id}") }, ", ".html_safe) %>
</p>

<p>
  <strong>Year:</strong>
  <%= @work.year %>
</p>

<div>
  <p><strong>Description:</strong></p>
  <p >
    <%= @work.description %>
  </p>
</div>

<p>
  <strong>Import row id:</strong>
  <%= @work.import_row_id %>
</p>

<p>
  <strong>Screenings:</strong>
  <%= safe_join(list_work_events(work_id: @work.id, role: 'film screened').map { |e| link_to(e.display_date, "/events/#{e.id}") }, ", ".html_safe) %>
</p>

<p>
  <strong>Cinefiles documents</strong>
  <a href='<%= "https://cinefiles.bampfa.berkeley.edu/?search_field=title_txt&q=#{@work.title}" %>'>Search</a>
  <br>

  <%= safe_join(list_cinefiles_thumbs(film_title: @work.title).map {|t| t.html_safe }, ", ").html_safe %>
</p>


<p>
  <strong>Wikidata ID:</strong>
  <%= @work.wikidata_id %>
</p>

<%= link_to 'Edit', edit_work_path(@work) %> |
<%= link_to 'Back', works_path %>